server:
  port: 10000
spring:
  application:
    name: member-service-provider # 配置应用的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置 alibaba 的数据库连接池
    password: MySQL123
    username: root
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useSSL=true&useUnicode=true&characterEncoding=UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定 mapper.xml 文件位置 classpath 表示 resources 目录下
  type-aliases-package: com.rainbowsea.springcloud.entity # 实例 bean 类所在的包,这样可以通过类名的方式

# 配置 eureka-client
eureka:
  client:
    register-with-eureka: true # 示将自己注册到 Eureka-Server,因为自己是作为 eureka-client客户端的角色的
    # 表示从 Eureka-Server 抓取注册信息
    # 如果是单节点，是可以配置的，但是如果是一个集群，则必须配置true
    # 才能配合 Ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # 表示将自己注册到那个 eureka-server
      # 将本微服务注册到多个 eureka - server 当中，使用逗号间隔即可
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
      # eureka 自我保护模式测试
#  instance:
#    # 客户端向服务端发送心跳的时间间隔为 1s (默认是30s)
#    lease-renewal-interval-in-seconds: 1
#    # 时间单位(秒)，默认是 90s，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
