server:
  port: 9001
# 配置 eureka-server
eureka:
  instance:
    hostname: eureka9001.com # 服务实例名或者别名
  client:
    # 配置不向注册中心注册自己,默认是 true
    register-with-eureka: false
    # 表示自己就是注册中心，作用就是维护注册服务实例，不需要去检索服务，默认是 true
    fetch-registry: false
    service-url:
      #设置与 eureka server 交互的模块,查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://localhost:9001/eureka/ ,也可以使用别名，在同一个文件当中可以引用
      # 相互注册，这里应用注册到 eureka server 9002 上
      defaultZone: http://eureka9002.com:9002/eureka/

  # 自我保护测试：下面两个设置，记得测试完要注释掉
#  server:
#    enable-self-preservation: false # 表示禁用自我保护模式，默认是没有禁用的为 true
#    # 设置超时时间为2秒，在 2秒钟，收不到心跳包，就认为是超时
#    eviction-interval-timer-in-ms: 2000

