server:
  port: 10004
spring:
  application:
    name: member-service-nacos-provider # 配置应用的名称
    # 配置 nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置注册到哪个 Nacos Server的地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置 alibaba 的数据库连接池
    password: MySQL123
    username: root
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useSSL=true&useUnicode=true&characterEncoding=UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定 mapper.xml 文件位置 classpath 表示 resources 目录下
  type-aliases-package: com.rainbowsea.springcloud.entity # 实例 bean 类所在的包,这样可以通过类名的方式

# 配置暴露所有的监控点:
management:
  endpoints:
    web:
      exposure:
        include: '*'

